# Generated by Django 3.2.16 on 2023-02-20 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='uniq_cart_recipe',
        ),
    ]
