# Generated by Django 3.2.16 on 2023-02-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_cart_uniq_cart_recipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='uniq_cart_recipe'),
        ),
    ]
